apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavanspring-deployment
  labels:
    app: pavanspring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pavanspring
  template:
    metadata:
      labels:
        app: pavanspring
    spec:
      containers:
      - name: pavanspring
        image: 522814735019.dkr.ecr.us-east-1.amazonaws.com/pavanspring:latest
        ports:
        - containerPort: 8080



---

apiVersion: v1
kind: Service
metadata:
  name: pavanspring-service
spec:
  type: LoadBalancer
  selector:
    app: pavanspring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

